services:
  webapioffer:
    container_name: webapioffer
    depends_on:
      postgresql:
        condition: service_healthy
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: dockerfile

  postgresql:
    container_name: postgresql
    image: postgres:latest
    environment:
      POSTGRES_DB: "offerstoredb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:

